// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Kamera
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public int? BrojTraka { get; set; }
        public bool Ufunkciji { get; set; }
        public int DionicaId { get; set; }
        public int VrstaKamereId { get; set; }

        public virtual Dionica Dionica { get; set; }
        public virtual VrstaKamere VrstaKamere { get; set; }
    }
}