// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Koncesionar
    {
        public Koncesionar()
        {
            Autocesta = new HashSet<Autocesta>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public string Email { get; set; }
        public DateTime KoncesijaOd { get; set; }
        public DateTime KoncesijaDo { get; set; }

        public virtual ICollection<Autocesta> Autocesta { get; set; }
    }
}