// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Odmoriste
    {
        public Odmoriste()
        {
            PopratniSadrzaj = new HashSet<PopratniSadrzaj>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public int DionicaId { get; set; }
        public int? KoordinataX { get; set; }
        public int? KoordinataY { get; set; }
        public int? GodinaOtvaranja { get; set; }

        public virtual Dionica Dionica { get; set; }
        public virtual ICollection<PopratniSadrzaj> PopratniSadrzaj { get; set; }
    }
}