// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class OdrzavanjeObjekta
    {
        public int Id { get; set; }
        public int VrstaId { get; set; }
        public string ImeFirme { get; set; }
        public TimeSpan RadnimDanomOd { get; set; }
        public TimeSpan RadnimDanomDo { get; set; }
        public TimeSpan? VikendimaOd { get; set; }
        public TimeSpan? VikendimaDo { get; set; }
        public int? BrojLjudi { get; set; }
        public int Cijena { get; set; }
        public int? PredvidenoDana { get; set; }
        public int? CestovniObjektId { get; set; }

        public virtual CestovniObjekt CestovniObjekt { get; set; }
        public virtual VrstaOdrzavanja Vrsta { get; set; }
    }
}