// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class ProlazakVozila
    {
        public int Id { get; set; }
        public string RegistracijskaOznaka { get; set; }
        public int KategorijaVozilaId { get; set; }
        public byte[] VrijemeProlaska { get; set; }
        public int NaplatnaKucicaId { get; set; }

        public virtual KategorijaVozila KategorijaVozila { get; set; }
        public virtual NaplatnaKucica NaplatnaKucica { get; set; }

        public static List<ProlazakVozilaTS> ConvertToProlazakVozilaTS(List<ProlazakVozila> pvl)
        {
            List<ProlazakVozilaTS> returnList = new List<ProlazakVozilaTS>();

            foreach(ProlazakVozila pv in pvl)
            {
                var pvTS = new ProlazakVozilaTS();
                pvTS.Id = pv.Id;
                pvTS.RegistracijskaOznaka = pv.RegistracijskaOznaka;
                pvTS.KategorijaVozila = pv.KategorijaVozila;
                pvTS.NaplatnaKucicaId = pv.NaplatnaKucicaId;
                returnList.Add(pvTS);
            }

            return returnList;
        }
    }
}