// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class Reakcija
    {
        public int Id { get; set; }
        public DateTime? Datum { get; set; }
        public string Opis { get; set; }
        public int IncidentId { get; set; }
        public int? VrstaReakcijeId { get; set; }

        public virtual Incident Incident { get; set; }
        public virtual VrstaReakcije VrstaReakcije { get; set; }
    }
}