// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class VrstaOdrzavanja
    {
        public VrstaOdrzavanja()
        {
            OdrzavanjeObjekta = new HashSet<OdrzavanjeObjekta>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public bool? Izvanredno { get; set; }
        public bool? Preventivno { get; set; }
        public string Periodicnost { get; set; }
        public string GodisnjeDoba { get; set; }

        public virtual ICollection<OdrzavanjeObjekta> OdrzavanjeObjekta { get; set; }
    }
}