// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class VrstaNaplate
    {
        public VrstaNaplate()
        {
            NaplatnaKucica = new HashSet<NaplatnaKucica>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }

        public virtual ICollection<NaplatnaKucica> NaplatnaKucica { get; set; }
    }
}