// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class VrstaReakcije
    {
        public VrstaReakcije()
        {
            Reakcija = new HashSet<Reakcija>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public string BrojTelefona { get; set; }

        public virtual ICollection<Reakcija> Reakcija { get; set; }
    }
}