// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models
{
    public partial class VrstaIncidenta
    {
        public VrstaIncidenta()
        {
            Incident = new HashSet<Incident>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public string OpisPravilaPonasanja { get; set; }

        public virtual ICollection<Incident> Incident { get; set; }
    }
}